### ISSUE TITLE
Selecting a location from search doesn't work

### ISSUE THREAD

**Issue by chk1** [sensebox/openSenseMap#194]
### Expected Behavior

In the "Search boxes" box I put a place name like "Ahaus" or "Münster". 

When I click on a result it should zoom to that location.

![image](https://user-images.githubusercontent.com/828496/28281310-ed4c61d0-6b26-11e7-8537-9d01417ad41a.png)

### Actual Behavior

When I click on a search result for a town or city nothing happens. There's a Javascript error in the console.

Selecting a senseBox from search works fine.

Chrome console error:

```
926319e0.vendor.js:1 TypeError: this.centerLatLng is not a function
    at e.d.selectBox (https://www.opensensemap.org/scripts/0d796393.scripts.js:1:31773)
    at fn (eval at compile (https://www.opensensemap.org/scripts/926319e0.vendor.js:1:142617), <anonymous>:4:323)
    at e.z.select (https://www.opensensemap.org/scripts/926319e0.vendor.js:1:1044655)
    at fn (eval at compile (https://www.opensensemap.org/scripts/926319e0.vendor.js:1:142617), <anonymous>:4:355)
    at p.r.(anonymous function) [as select] (https://www.opensensemap.org/scripts/926319e0.vendor.js:1:60836)
    at e.selectMatch (https://www.opensensemap.org/scripts/926319e0.vendor.js:1:1047807)
    at fn (eval at compile (https://www.opensensemap.org/scripts/926319e0.vendor.js:1:142617), <anonymous>:4:328)
    at e (https://www.opensensemap.org/scripts/926319e0.vendor.js:1:83805)
    at r (https://www.opensensemap.org/scripts/926319e0.vendor.js:1:165565)
    at e.$eval (https://www.opensensemap.org/scripts/926319e0.vendor.js:1:93893) undefined
```

### Environment
- OS: Windows 7
- Browser & Version: Firefox 54, Chrome 59

**Comment by mpfeil** [comment]
fixed in https://github.com/sensebox/openSenseMap/commit/84b67050336c8fbf3ebf0fbe1ba43dcc94aaba5c

will be online tomorrow
